/***** DO NOT EDIT THIS FILE *****/
// UnityTutorialProject.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var UnityTutorialProject = {};

/*** script -- MyFirstTest ***/
UnityTutorialProject.MyFirstTest = function(app) {
	MT.Script.call(this, app, "MyFirstTest.mt");
};

UnityTutorialProject.MyFirstTest.prototype = new MT.Script;

UnityTutorialProject.MyFirstTest.prototype.call = function(usr, pwd, _name) {
	//run: MyFirstTest.mt
	MT.Script.prototype.call(this, usr, pwd, _name);
};

MT.Application.prototype.myFirstTest = function() {
	return new UnityTutorialProject.MyFirstTest(this);
};

